### ISSUE TITLE
Bug: Multiline Enum descriptions get lost towards RAML_DOC

### ISSUE THREAD

**Issue by nkuehn** [commercetools/rmf-codegen#264]
resolves: https://github.com/commercetools/commercetools-docs-kit/issues/1142 

test input:
```yaml
  EnumWithDescriptionExample:
    description: Enum with agreed upon description annotation.
    type: string
    (annotations.enumDescriptions):
      enumValue1: Description 1
      enumValue2: |
        Description 2 with a line break (first line)
        Second line.

        New paragraph.
      enumWithMarkdownDescription: |
        `inline-code` should be formatted as an inline code. [ObjectTestType](/types/general#objecttesttype) should link to the header of the definition of `ObjectTestType` on this website - `api-docs-smoke-test`. [Links](/../docs-smoke-test/views/markdown#links) should link to the header for the definition of  `Links` on `docs-smoke-test` microsite.
    enum:
      - enumValue1
      - enumValue2
      - enumWithoutDescription
      - enumWithMarkdownDescription
```

current output in RAML_DOC:

```yaml
#%RAML 1.0 DataType
displayName: EnumWithDescriptionExample
description: |-
  Enum with agreed upon description annotation.
type: string
enum:
- enumValue1
- enumValue2
- enumWithoutDescription
- enumWithMarkdownDescription
(enumDescriptions):
  enumValue1: "Description 1"
  enumValue2: "Description 2 with a line break (first line)nSecond line.nnNew paragraph."
  enumWithMarkdownDescription: "`inline-code` should be formatted as an inline code.
   [ObjectTestType](/types/general#objecttesttype) should link to the header of the
   definition of `ObjectTestType` on this website - `api-docs-smoke-test`. [Links](/../docs-smoke-test/views/markdown#links)
   should link to the header for the definition of  `Links` on `docs-smoke-test`
   microsite."
```

The multiline string gets lost in the RAML_DOC output. Newline markers appear as literal `n` characters.
