### ISSUE TITLE
RAML Doc generator loses content type for file types

### ISSUE THREAD

**Issue by stmeissner** [commercetools/rmf-codegen#313]
### Context

When I have a POST body of type `file`:

```
post:
  displayName: Upload an image
  queryParameters:
    filename:
      required: false
      type: string
      (builtinType): string
  headers:
    Content-Type:
      type: string
      (builtinType): string
      required: true
  body:
    type: file
    fileTypes:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
```
### Current behavior

The RAML Doc generator turns it to `application/json`:

```
  body:
    application/json:
      fileTypes:
        - "image/jpeg"
        - "image/png"
        - "image/gif"
      type: file
      (builtinType): file
```
### Expected behavior

The type stays as it was:

```
  body:
    type: file
    fileTypes:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
```
